### PR TITLE
fix duplicate spec.provider.oracle.auth.secret_ref.privatekey in exte…

### PR DESCRIPTION
**Pull request by antoniolago**
…rnal_secrets_io docs

### CODE REVIEW

**Comment by sebhoss** [comment]
Hey thanks for bringing this to my attention and even providing a fix for it!

Unfortunately I cannot merge this because it would break the current build process. At the moment the entire documentation is automatically generated using https://github.com/hashicorp/terraform-plugin-docs. The 'verify' pipeline will run this tool and check whether there are changes in the worktree. If it detects changes, the build will fail prompting the maintainers to re-run the documentation generation.

That said, the fix you provided is correct! I just need to investigate why the documentation generation does make a mistake here (and potentially elsewhere).

**Comment by sebhoss** [comment]
I'm still not sure why this is happening so I've created https://github.com/hashicorp/terraform-plugin-docs/issues/285 to get some help.

**Comment by antoniolago** [comment]
That makes sense 😅

I'll close this PR for now, but glad it brought light into this problem, I'll be following that issue, thank you so much.

Nice project btw.

**Comment by sebhoss** [comment]
I finally found some time to look deeper into this and opened https://github.com/hashicorp/terraform-plugin-docs/pull/350 to fix this. I think this bug affects many providers in the ecosystem, so thanks again @antoniolago for opening this!

The latest version of this provider uses my patched version of terraform-plugin-docs and it seems to work as expected.

**Pull request closed without merging**
